### ISSUE TITLE
Libsdisguises and vanishnopacket

### ISSUE THREAD

**Issue by KanjiOkami** [libraryaddict/LibsDisguises#101]
Is it possible to have the disguise take priority over vanishnopacket? With disguisecraft we were able to disguise without unvanishing but with that plugin barely working and having more interest in some of the other features libsdisguises has we tried switching over only to find out we have to unvanish to have the disguise be seen. Is there a way to change that?

We also tried libsdisguisecraft to no avail.

**Comment by NavidK0** [comment]
I haven't used VanishNoPacket recently, so I'm assuming invisibility is a status effect, in which case the invisibility transfers over to disguises. There's not really a way to prevent this - LibsDisguises works by applying everything the player has (status, potions, inventory) to the disguise. Disguises in LibsDisguises do not spawn actual server mobs, they're all client side mobs, so in order to change their invisibility, you would have to make an API call to LibsDisguises and set the disguise's invisibility flag in the FlagWatcher to true.

I'm not going to add VanishNoPacket support into LibsDisguises, as it it requires me to add a dependency to LibsDisguises other than ProtocolLib, and since LibsDisguises is also an extensive API for developers, I don't want to bloat it further with external APIs.

You could always ask VanishNoPacket's developer to add the feature you are looking for, or you could make a custom plugin that adds this functionality.

I hope this answers your question. I could always add an option to disable things like invisibility/status effect transfers, but then you lose a lot of functionality.

**Comment by KanjiOkami** [comment]
Vanishnopacket doesnt use potion effects, to my knowledge it uses the bukkit vanish api or so I read somewhere on their github. Dont know if that changes anything.

**Comment by NavidK0** [comment]
It still uses a status effect which is transferred over to the disguise, you can confirm this by looking in your inventory, it should show "Invisibility"

**Comment by KanjiOkami** [comment]
Nope, only effect I have is nightvision from a potion I drank.

**Comment by NavidK0** [comment]
It might just be Essentials /vanish that does that then, as it shows Invisibility when I use it. I'll have to look more into how VanishNoPacket works before I make any changes regarding this.

**Comment by KanjiOkami** [comment]
Alright, ill keep in eye out for any developments in the meantime then. I will also see if there is anything they can do to help as well.

**Comment by leasoncre** [comment]
i use supervanish (i prefer the action-bar support/ on-screen-notice) 
can support/comparability for that be added as well?
