### ISSUE TITLE
Strangeness with 2 disguisers

### ISSUE THREAD

**Issue by dumptruckman** [libraryaddict/LibsDisguises#107]
Using the beta for 1.9. I noticed that I now see an outline of my original self when disguised which is pretty cool. However, when another admin disguised that outline disappeared. In addition, whenever the outline disappears I can no longer stand still - I constantly drift around.

**Comment by NavidK0** [comment]
This happens because 1.9 adds wonderful player collisions, meaning if I don't add the player to a Team and set its collision rule to "NEVER", the disguises will push the player. As far as I know, it is currently the only way to solve this (thanks Mojang).

It is indeed a bit buggy, the current workaround is to type /vsd a couple of times until your outline shows up again.
