### ISSUE TITLE
Disguise moving player randomly

### ISSUE THREAD

**Issue by datatags** [libraryaddict/LibsDisguises#109]
Bottom line:  When I am disguised as a player, my disguise moves me randomly.

I just tested LibsDisguises 9.0.1, with ProtocolLib 3.7.0 beta, and the latest Spigot, downloaded 10 minutes ago, and the disguise moved me.  Literally.  I held a sword in my left hand, a shovel in my right hand, disguised myself as Notch, walked around, and it seemed to work fine.  The problem came when I stopped.  The disguise started moving slowly in a random direction and taking me with it.  I undisguised myself, and it stopped.  I redisguised myself, moved, and it did the same thing.  I tried this a few times, and got the same result every time.  Let me know if you need more information.

**Comment by NavidK0** [comment]
I described this on the Spigot forums:

"Currently there's an issue where the disguises may occasionally push players around, but it can be fixed by undisguising and disguising again, or toggling /vsd on and off. I plan to have this fixed once there's an official way to disable player pushing, but until then, I have to stick with a ruddy scoreboard system."

There is a scoreboard system in place that should stop this from happening, but it doesn't always work.

There's really nothing that can be done about this at the moment. Type in /vsd  to disable third person disguises, or disable it in the config. It happens because 1.9 added player collisions, and unfortunately, there's no simple way to disable collisions without scoreboards. I'm waiting for a Spigot update or something similar to add API for this, otherwise, this will continue to be a problem.
