### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ChavitaHD** [libraryaddict/LibsDisguises#224]
Hello, I was wondering, if it would be possible to make all the messages that the plugin shows would be able to be changed via a lang.yml file of some sort?

**Comment by libraryaddict** [comment]
Its possible, but I'd be making that a premium-only feature and I'd almost have to auto generate the translation file.
Its just not very high on my todo

**Comment by ChavitaHD** [comment]
I would gladly pay to be able to edit the messages!

**Comment by libraryaddict** [comment]
The funny thing about payment however is that when its a sum I would find agreeable, people tend to get upset.

**Comment by ChavitaHD** [comment]
I meant as in purchasing a copy of the premium one, as you said it would be a premium feature. But I understand custom plugins and custom modifications are very expensive, I completely understand.

**Comment by libraryaddict** [comment]
mm np.
I've done some basic work on it, however the major problem is that while translating the messages is simple enough. There's also the part where I need to detranslate and the methods translate and so on.

**Comment by ChavitaHD** [comment]
Hmm, what about the setting your disguise and undisguising.

**Comment by libraryaddict** [comment]
I don't like half-assing things

**Comment by ChavitaHD** [comment]
Haha, I understand, I will be waiting, let me know if you end up doing it.

**Comment by libraryaddict** [comment]
Oh I'm working on it now

**Comment by libraryaddict** [comment]
Try the latest build, you will need to have purchased the plugin but this should allow almost full translations for all textual stuff.

I say almost because I don't allow you to change /libsdisguises and some minor stuff like listing all the disguises you can use, I don't let you change the formatting.

Its not that tested beyond checking it works, you should be able to translate the options so you can use

/disguise sheep fireItUp true

So instead of setBurning you translate it to fireItUp

Again, not tested.

**Comment by libraryaddict** [comment]
This is now in the latest dev builds
