### ISSUE TITLE
Version 8.6.7

### ISSUE THREAD

**Issue by GonzaGamer123** [libraryaddict/LibsDisguises#225]
Hello, I have a problem in finding the version 8.6.7 for the server 1.8 is that in the page of spigot is wrong the one that walks and the one that is the link is fallen could I pass the file you?

**Comment by libraryaddict** [comment]
Sorry but I don't have those jars

**Comment by Matocolotoe** [comment]
So how can we make this plugin work for 1.8 @libraryaddict ?
(Don't tell me that you don't support 1.8, I'm tired of seeing everybody thinking this is an outdated version)
The real "8.6.7" jar is unavailable but the 8.6.8, for newer versions, is still downloadable.

**Comment by libraryaddict** [comment]
> I don't think that releasing something that a lot of people need for their server is hard

This is an open source plugin :)

**Comment by Matocolotoe** [comment]
A plugin is made to be downloadable by, most of the time, non-developer players
Moreover it's just a **simple packet and ProtocolLib compatibility problem**, everything else is stable in 1.8. Still can't get it.

**Comment by libraryaddict** [comment]
Make a PR on a new branch for 1.8 and I'll accept it.

**Comment by libraryaddict** [comment]
So are

**Comment by Matocolotoe** [comment]
There is a difference between "it's simple" and "a simple error"
I just mean that it's a **single** error about packet things
But nevermind, there is 1 big other in 1.8 that cancels any right-click after undisguise...

**Comment by libraryaddict** [comment]
You said you wanted the entire plugin downgraded to 1.8, that's not simple.

I've had a long day, and I don't get many hours to myself. My breaks was spent replying to your messages, and I'm tired. You can see I accidentally opened the issue. Then closed it.

I don't have a reason to do it. I don't care about older versions of Minecraft, and it's not a copy/paste job. It would involve a week of work including weekends which I generally have free; at my best estimate. Realistically? 2-3 weeks. It's really not profitable in terms of time taken. How many people would use it? Maybe quite a few. Need it? Not many.

Even a literally simple change isn't likely to happen, because I don't think more than a few people would care. Or even notice, given they would already be using the 1.8 version of the plugin.

New servers shouldn't normally be on 1.8, new servers as a rule use the latest version of MC.

**Comment by Matocolotoe** [comment]
I just said there is a single error to be fixed.
And nevermind, I'm too lazy to answer to something containing so much hate against older versions of Minecraft that people still use because statistics, main argument of 1.9+ users, can prove that more than 20% of the servers are in "old" versions.
I'll just go fuck myself and learn Java to make 1.8 things.
