### ISSUE TITLE
Problem with the disguise

### ISSUE THREAD

**Issue by XeresFG** [libraryaddict/LibsDisguises#277]
When trying to turn a body into chest blocks, ender_chest or trapped_chest the entity becomes invisible

**Comment by libraryaddict** [comment]
Sorry but this won't be fixed as it's an issue with the disguises you picked, not the plugin itself.

**Comment by sgdc3** [comment]
@libraryaddict what do you mean?

**Comment by libraryaddict** [comment]
Because of the way Minecraft renders certain blocks, such as chests. They do not render properly as a falling block.

This breaks them and makes it invisible.
The most I could do from my perspective is to disable them completely, but then I'd need to start maintaining a list of blocks you may not disguise as which I find a bit.. Annoying.
