### ISSUE TITLE
Permission issue and luckperms

### ISSUE THREAD

**Issue by xion87** [libraryaddict/LibsDisguises#307]
Hi i just tried enfacing a strange issue by using luckperms and libsdisguise
Basically a special group have these permission:
libsdisguises.disguise.(JOLLY).(JOLLY)

Since i would disable the slime "setsize" option i set false this permission
libsdisguises.disguise.slime.setsize

But doing that, the that group was unable to use the slime disguise anymore, i asked to luckperms support but they don't find any clue if is a issue with LP, so i try to ask to you.

**Comment by xion87** [comment]
i already tried, It allow to use fully the Slime without any limit

**Comment by libraryaddict** [comment]
And you cannot use any other disguises right?

If you're op or have * then it'll still bypass that.

**Comment by xion87** [comment]
exact i am testing as normal user, not as staff

**Comment by libraryaddict** [comment]
I could only reproduce when using multiple permission plugins.

And even then, the fault was in one of the permission plugins disabling itself.

**Comment by libraryaddict** [comment]
Actually, just re-read your original problem and you're doing it wrong.

You're supposed to use "libsdisguises.disguise.slime.-setsize" not "-libsdisguises.disguise.slime.setsize"

However I'll add this in the next snapshot.

**Comment by xion87** [comment]
I have used "lp group vip permission set libsdisguises.disguise.slime.-setsize false

**Comment by libraryaddict** [comment]
Try the new snapshot, does this solve your issue?

**Comment by xion87** [comment]
The server is in 1.12.2...
[09:19:28] [Server thread/ERROR]: [LibsDisguises] You're using the wrong version of Lib's Disguises for your server! This is intended for 1.13!
[09:19:28] [Server thread/INFO]: [LibsDisguises] Disabling LibsDisguises v9.6.0-SNAPSHOT

**Comment by xion87** [comment]
I am testing the vip rank
I added 
libsdisguises.disguise.(JOLLY).(JOLLY)
+
libsdisguises.disguise.slime.-setsize

With that i can still use slime and all options

**Comment by xion87** [comment]
i know before on powerfulperms these special perms are working, instead on luckperms nope...

**Comment by libraryaddict** [comment]
Ah, I see your issue.

You have defined

"libsdisguises.disguise.mob" to give the players all the permissions for mobs.

Then you used

"-libsdisguises.disguise.slime.setsize" to negate the slime option on the above permission.

However, the way the plugin works is that it treats each permission as separate on what they can use.

So you could set
"libsdisguises.disguise.slime.setburning"
and
"libsdisguises.disguise.slime.setsize" 
so they can use setsize or setburning, but not both on the same disguise.

I'll leave this ticket open, but my thoughts are that instead of having negated permissions treated the same as a
"libsdisguises.disguise.slime.-setsize"
it should work as you expected, negate permissions on _other_ disguises despite their not declaring this on their permission.

Otherwise a negated permission that declares options doesn't do anything new.

Hmm, would a negated permission that negates options, allow those options...
