### ISSUE TITLE
Show item in main hand but not armour

### ISSUE THREAD

**Issue by theonlygusti** [libraryaddict/LibsDisguises#314]
I want all other plays to be able to see what I (when disguised as a mob) am holding, but not what armour I am wearing.

looks like `constructDisguise` sets either _both_ armour and weapon as visible, or neither.

**Comment by libraryaddict** [comment]
What do you believe constructDisguise is for?

That section of the API is provided to create a disguise off an existing entity, if you want to create your own disguise you can construct it with "MiscDisguise" "MobDisguise" and "PlayerDisguise"

You can also use the FlagWatcher from the disguise to show/hide the items.

Setting it to null will show armor if you're wearing air, while setting it to air will hide your real armor. And finally, setting it to a real item will show that item instead.

Does this answer your question?

**Comment by theonlygusti** [comment]
@libraryaddict so would I do something like 

```java
MobDisguise skeletonDisguise = new MobDisguise(DisguiseType.SKELETON);

skeletonDisguise.getWatcher().setArmor({new ItemStack(Material.AIR)});
```

**Comment by libraryaddict** [comment]
No I don't believe so, because while it seems pretty long-winded I don't think I would've implemented another solution to fix that.

The reason being that normally, no one wants to use that. Instead they want to set different items on each part of the body.

Does your provided answer work for you satisfactorily, despite the long-windedness of the code?

**Comment by theonlygusti** [comment]
I will have to test it but I assume it will work.
