### ISSUE TITLE
Incompatibilities with other ProtocolLib plugin

### ISSUE THREAD

**Issue by fensoft** [libraryaddict/LibsDisguises#320]
When using bungee + premium LibsDisguises in 1.13 + a very simple ProtocolLib plugin, it makes minecraft vanilla crashing in bungee (and only if bungee is used).

I don't know if it's a bug in bungee but clearly LibsDisguises is modifying my packets and makes bungee crashing with this error:
`DecoderException : java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 65536)) @ io.netty.handler.codec.MessageToMessageDecoder:98`

I've made a very simple sample of my plugin to show you this. Just open the inventory and click on any item or even an empty (AIR) slot:
```
package com.fensoftheberge.FenProtocolLib;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.plugin.Plugin;
import org.bukkit.plugin.java.JavaPlugin;

import com.comphenix.packetwrapper.WrapperPlayServerSetSlot;
import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.ProtocolLibrary;
import com.comphenix.protocol.events.PacketAdapter;
import com.comphenix.protocol.events.PacketEvent;

public class FenProtocolLib extends JavaPlugin {
	class WindowClickPacketListener extends PacketAdapter {
	        public WindowClickPacketListener(Plugin plugin) {
	            super(plugin, PacketType.Play.Client.WINDOW_CLICK);
	        }
	        
	        @Override
	        public void onPacketReceiving(PacketEvent event) {
	        	WrapperPlayServerSetSlot packet_setcursor = new WrapperPlayServerSetSlot();
	        	packet_setcursor.setSlot(-1);
	        	packet_setcursor.setWindowId(-1);
	        	packet_setcursor.setSlotData(new ItemStack(Material.AIR));
	        	packet_setcursor.sendPacket(event.getPlayer());
	        }
	}

	public void onEnable() {
    	ProtocolLibrary.getProtocolManager().addPacketListener(new WindowClickPacketListener(this));
    }
}
```

Here's the versions i'm using:
```
Paper version git-Paper-435 (MC: 1.13.2)
ProtocolLib v4.4.0*
LibsDisguises v9.6.0-SNAPSHOT + premium LibsDisguises-9.5.2.jar
BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:c26705e:1368

```

**Comment by libraryaddict** [comment]
Not sure if that packet is valid, but you can disable packet handling in the config

**Comment by fensoft** [comment]
Default config, i've changed: this to false and now it works:
RemoveArmor: true

Any idea why it's doing this ?

**Comment by libraryaddict** [comment]
You are catching that packet on an async thread, then sending it async. To my knowledge, all packets received from the client are done async. All packets sent from the server are sync.

I'm also guilty of sending packets async, but in this scenario I'm innocent.

Only because I have the packets registered does the problem occur. Even if nothing executes, your problem still occurs.

I believe this is a ProtocolLib bug in that it lets you do this, and BungeeCord likely comes into play with the way it handles packets.

Send your slot packet in a scheduler, or register your listener as sync. It should work then.

`ProtocolLibrary.getProtocolManager().getAsynchronousManager().registerAsyncHandler(new WindowClickPacketListener(this)).syncStart();`

**Comment by fensoft** [comment]
Oh, god. What a tricky "bug", it's probably just a bug of packet ordering.
Thanks a lot for investigation and this huge explaination !
I'll contact ProtocolLib and/or BungeeCord.
