### ISSUE TITLE
Why does the disguises lag so far behind the player?

### ISSUE THREAD

**Issue by theonlygusti** [libraryaddict/LibsDisguises#343]
Even when I host the server myself, so less than 0.05 ms ping, the disguise is never where the player is (if the player is moving) it's always lagging behind and often doesn't even follow the path the player takes, but often a shortcut. E.g. if the player is just jumping in one spot the disguise often doesn't even touch the ground and has a strange easing effect, going up and down like a sine wave instead of how the player moves.

What causes this effect and can I minimise it?

**Comment by libraryaddict** [comment]
The server is showing you a fake entity, your client doesn't control it.

So you're seeing what you look like, to yourself.

If the server didn't control it, there would be no self disguise as the client only controls their own player. So the server is required to send the disguise otherwise it will not show at all. And because the server controls it, it means it's not a perfect 1:1 movement of the player.

The server isn't as fast as you think it is, the movement lag is only noticeable because you know exactly when it should've been moving.

**Comment by theonlygusti** [comment]
@libraryaddict to other players, is the disguise always in exactly the same place as where the player entity would be?

**Comment by libraryaddict** [comment]
Yes, it's only because you're controlling the disguise itself do you notice that there's a tiny bit of lag between you and the server.

It's like when you break a block, you actually don't break it immediately according to all the other players. But you think you did, and that's what matters.

If you run two clients and break a block with one of them, you'll notice it's not instant on the other client, despite being on the lowest ping possible.
