### ISSUE TITLE
Spammed console error

### ISSUE THREAD

**Issue by Momshroom** [libraryaddict/LibsDisguises#354]
Using Libsdisguises build 273, with the premium jar in the folder. 
Protocol Lib 4.4.0 release
Spigot 1.13.2

I'm not sure what's triggering this one.
https://pastebin.com/5UgbjVCb

**Comment by Momshroom** [comment]
Yes, it still happens in build 274.  It's an occasional error so I had to check a few logs before finding it again.

**Comment by libraryaddict** [comment]
Interesting, looked at it again and it is different from the bug I fixed.

In your case, I know what should be making the error but I'm not sure where the problem is coming from. I've just looked at the code again and it doesn't seem to have any issues so I'm curious what's happening here.

Unfortunately, without more information I'm not sure I can help.

Do you happen to know what the disguise is, and what settings are on that disguise?

The error should occur because either a player left the game, or an entity was in a chunk that was unloaded.

**Comment by Momshroom** [comment]
I suspect it’s due to one of our mythic mob disguises.   I’ll test my
theory and send you the disguise info if I’m correct.

**Comment by Momshroom** [comment]
Yes, the error occurs when a mythic mob which is disguised as a fireball is in a chunk that is unloaded.  It's just configured as disguise type: fireball

**Comment by Momshroom** [comment]
I get the same error if I just do /d fireball and log out.

**Comment by libraryaddict** [comment]
Try the latest dev build, your issue should be resolved.

**Comment by Momshroom** [comment]
It is.  Ty
