### ISSUE TITLE
Why do you depend on spigot and spigot-api

### ISSUE THREAD

**Issue by theonlygusti** [libraryaddict/LibsDisguises#355]
what's the difference between both of these, I thought you only needed to depend on one of them

also why are you depending on 1.13-R0.1-SNAPSHOT when 1.13.2-R0.1-SNAPSHOT is already out

**Comment by libraryaddict** [comment]
Spigot-API offers the common API's that everybody uses, but the api doesn't cover a few tools that the spigot jar itself does.

I'm not sure what currently depends on the spigot jar, but decoupling it from the project has resulted in failure.

I also depend on spigot-api even though spigot technically does the same thing, because spigot is not a real API and trying to use it as such can result in bad or malformed API calls.

The plugin is dependent on an older version of spigot because, I never got around to updating it and there's been no issues.

Lib's Disguises does not directly call NMS methods and classes, so it does not need to depend on a specific version of Spigot.

However, I'll make a note to update spigot to the latest version in the next commit.
