### ISSUE TITLE
squid velocity messes up in 1.8

### ISSUE THREAD

**Issue by realdiv** [libraryaddict/LibsDisguises#404]
Whenever a squid disguise velocity is changed by setVelocity it starts glitching out. Someone else has brought this up before (issue 348) but I wasn't able to fix it with the response you gave. If you could direct me to the code that fixed this in later versions that would be very helpful.

**Comment by libraryaddict** [comment]
Sorry but its been a while since I messed with squids velocity.

If I recall correctly, it's because the squids velocity isn't naturally decayed while normal mobs has a natural decay.

So there may not be an actual real answer here. I'm not sure if there's another answer and I solved it there.
A solution may be to negate all squid velocity altogether, which you can do by modifying the velocity packet and checks on the spawn packet.
