### ISSUE TITLE
TAB compatibility

### ISSUE THREAD

**Issue by Lusteroth** [libraryaddict/LibsDisguises#418]
Is it possible to show TAB nametags above your head when you are disguised as a mob?

https://github.com/NEZNAMY/TAB/issues/6

**Comment by libraryaddict** [comment]
Lib's Disguises already does.

The reason TAB doesn't work properly is because it doesn't use the official Bukkit api to modify scoreboard and scoreboard teams. I'm not sure why it avoids it so badly, but basically.

What TAB is doing is hiding these changes from other plugins, unless they ask TAB for information on it. And unless its a fault in Lib's Disguises, I have no intentions to add hooks into other plugins.

Recommended Fix? TAB should either actually use scoreboards and scoreboard teams, or you should switch plugins.

**Comment by NEZNAMY** [comment]
> What TAB is doing is hiding these changes from other plugins
This is only applied when player list in the packet contains names of online players. It does not prevent packets containing other entities (identified by uuid) from being sent. Simple proof is that if it did this, none of the animation supporting sidebar scoreboard plugins would work with it. But they do.
