### ISSUE TITLE
Enhancement: Bypassing disguise character limit via scoreboard prefix/suffix

### ISSUE THREAD

**Issue by UltraFaceguy** [libraryaddict/LibsDisguises#422]
In theory, it should be possible to have a name longer than 16 chars above player disguised entities, using scoreboard teams. So this is basically just a request for optional support for using a scoreboard prefix/suffix for player disguises. Mostly so renamed mobs can have full names with color codes and such.

**Comment by libraryaddict** [comment]
My main thoughts on this is that it means Lib's Disguises would pretty much need to create custom player names for everyone that uses this feature, otherwise you can't do "Level 2 Notch" and "Level 3 Notch"

By custom player names, I mean "Notch&1" and so on. Would only throw an error if the disguise has no leeway for spare characters. So 16 + 16 + 16 = 48 characters. Where it needs 46 chars at min and preferably 6 chars to itself for chatcolors.

Not an issue in itself, though it would result in "team spam". Can be cleaned up with unique team names, also is an idea to fallback to this if the provided player name is larger than 16 characters.

My main reason for not implementing it now is time.

**Comment by UltraFaceguy** [comment]
It could possibly be ignored for players disguising as this entity, instead using the trimmed name, and only be reserved for applying it to non-players, at least initially. My particular is use case of libs is as an RPG server, and only non-player entities receive these disguises, which would avert this problem. Though I'd imagine this wouldn't be the most intuitive, and you'd get frequent questions from people who can't read a wiki/source code.

Well, anyways, didn't see it so I thought I ought to put it on the list. Thanks if you do find the time to implement 👍

**Comment by libraryaddict** [comment]
Actually I'm working on it now, so.
