### ISSUE TITLE
Disguises Push you when disguised

### ISSUE THREAD

**Issue by NXxEpicXCreeperxX** [libraryaddict/LibsDisguises#504]
is there a fix to stop disguises pushing you?
My player is very mad and we need it fixed!

**Comment by libraryaddict** [comment]
Extract from discord bot.

So, you have issues where your self disguise is pushing you around and making you glide?
First things first, try `/ld scoreboard`, that plugin will do a quick scan of your server to determine if there's an issue it can find.

But most issues are caused by a fancy tablist, or nametag plugin. Why? Because most plugins do things the lazy way without regards as to the compatibility of other plugins.
Check their configs to see if you can disable pushing, in TAB for instance, change enable-collision: true to enable-collision: false

If you're still having issues after this, try removing plugins one by one until the issue disappears. Then report the problem to the author of that plugin
I can't really help you more if you don't try to do some work on your end ;)

**Comment by NXxEpicXCreeperxX** [comment]
okay, i coudln't find the discord here so Ill try

**Comment by NXxEpicXCreeperxX** [comment]
I don't have nametagedit though but i will check my tab plugin

**Comment by NXxEpicXCreeperxX** [comment]
I don't see any Push thing iN TAB plugin I use i believe its just called TAB as the folders called

**Comment by libraryaddict** [comment]
change enable-collision: true to enable-collision: false

**Comment by NXxEpicXCreeperxX** [comment]
where? in libsdisguises?

**Comment by libraryaddict** [comment]
In tab

**Comment by NXxEpicXCreeperxX** [comment]
I don't see it in the tab plugin, where is it?

**Comment by libraryaddict** [comment]
Try regeneration the config

**Comment by NXxEpicXCreeperxX** [comment]
Okay thank you!

**Comment by NXxEpicXCreeperxX** [comment]
Why can't I use fireworks or some items when disgusied?

**Comment by libraryaddict** [comment]
Turn off equipments stuff on config

**Comment by NXxEpicXCreeperxX** [comment]
Okay thank you! Thanks again! this can be closed now

**Comment by NXxEpicXCreeperxX** [comment]
Wait a sec, is there a way to hide your elytra when disguised? I have 2 the one im wearing and the diguesed one, I turned ot equipment but that didnt wokr

**Comment by libraryaddict** [comment]
If I hid your eltra, you couldn't glide. You can hide it on the disguise, use setChestplate

**Comment by NXxEpicXCreeperxX** [comment]
Is that in the config?

**Comment by libraryaddict** [comment]
No.

/disguise player Notch setchestplate air

**Comment by NXxEpicXCreeperxX** [comment]
Yea, but I want the disguise to show off the elytra and hide my player elytra

**Comment by NXxEpicXCreeperxX** [comment]
Oh, other people can see the elytra but i can only see mine, weird
