### ISSUE TITLE
No ability to setSitting for Player

### ISSUE THREAD

**Issue by WhoviV** [libraryaddict/LibsDisguises#619]
Hi, I'm unsure if this due to any issues on the side of Minecraft, or if I'm overlooking something, but when disguising as a Player, there's options for majorly every possible pose, except for sitting.

Other entities have this tag available. Is the addition of the tag for Players possible?

Thanks

**Comment by libraryaddict** [comment]
Because its not actually a real thing.

Instead, I'd have to spawn another entity for the disguise to sit on.

I'm not sure how you're doing the disguises, but an option is to disguise the entity as an invisible entity, then spawn another entity to ride the disguised entity. And disguise that entity too.

Or just don't disguise the first entity and give them invisibility.
