### ISSUE TITLE
Jenkins build # 13 (new one) player kicked when disguise as other player

### ISSUE THREAD

**Issue by sholan** [libraryaddict/LibsDisguises#68]
When issuing command /disguise player Notch,
I got kicked from my server.

## Kick message :
```
Internal Exception:
io.netty.handler.codec.DecoderException:
java.lang.IndexOutOfBoundsException:
readerIndex(1) + length(1) exceeds writerIndex(1):
UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 1)
```

## First line of stack trace in latest.log :
java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.PacketPlayOutPlayerInfo$EnumPlayerInfoAction

## Full stack trace :
http://pastebin.com/bG6igCiK

## Softwares involved :
Spigot 1.8.3
ProtocolLibs 1.8.3 (jenkins build #114 : http://ci.shadowvolt.com/job/ProtocolLib/114/ )
LibsDisguises jenkins build #13 ( http://www.psmc.ca:8080/job/LibsDisguises/13/ )

Do not hesitate to let me know if you need more informations

regards,
sholan

**Comment by NavidK0** [comment]
Another person had this issue remedied by  updating their ProtocolLib version. The stack trace error:
net.minecraft.server.v1_8_R1.PacketPlayOutPlayerInfo$EnumPlayerInfoAction leads me to believe that you didn't actually update your ProtocolLib version or LibsDisguises versions to the latest versions.

Make sure you absolutely update them both, because java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.PacketPlayOutPlayerInfo$EnumPlayerInfoAction means that it cannot find a class that is only present in Spigot 1.8.3 and higher.

**Comment by sholan** [comment]
Just update with latest versions LibsDisguises jenkins #14 and Protocolib jenkins #114 and it's working fine, thank you !
