### ISSUE TITLE
Custom name not displaying above disguise.

### ISSUE THREAD

**Issue by xYourFreindx** [libraryaddict/LibsDisguises#85]
I've been tinkering with my code in every way I could imagine for the past four hours, and for the life of me, I can't seem to get my disguises to display their custom name.
Which is weird, because the Libsdisguises plugin's disguises display the custom name properly, and I've looked at exactly how the plugin does it... I'm doing it the same way, only with no positive results.
(I have tested this only on MobDisguises, as that's all I'm using in my minigame. No idea on the player disguises)
```java
disc.getWatcher().setCustomName(getPlayer().getName());
disc.getWatcher().setCustomNameVisible(true);
```
Casting the watcher to a LivingWatcher does not help. 
The two methods are already available in the FlagWatcher class, contrary to what the spigot wiki says.

**Comment by xYourFreindx** [comment]
But seriously, xD
Those methods are available in the superclass FlagWatcher, making them available in all of it's subclasses...
So why do you keep unnecessarily casting to the subclass LivingWatcher when trying to access them?
Color me confused.

**Comment by NavidK0** [comment]
LibsDisguises is quite an old plugin, two years strong now. I'm sure it was just an oversight at the time, you know how developers like to code at night. :coffee: 

As far as the custom name not being set, quite a few users have complained about custom names not working in 1.8 due to data values changing, and I'm not sure why they are broken. It's likely that by 1.9 comes out, ALL the data values are going to have to be remapped due to the dynamic datawatcher, and it's going to take eons.

**Comment by xYourFreindx** [comment]
Welp.... Shet...

**Comment by NavidK0** [comment]
Issue here:
https://github.com/libraryaddict/LibsDisguises/issues/89
